app = "upbit-predictor"
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  TELEGRAM_TOKEN = "7994021618:AAG14Rf9frHyQ-0IWnj54kuX6Bm1OQ0z0ak"
  CHAT_IDS = "1901931119"
  SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/*********/*********/*********"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
